# Generated by Django 4.2.16 on 2024-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veg_recipe",
            name="recipe_name",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
