# Generated by Django 4.2.16 on 2024-09-20 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("veg", "0002_veg_recipe_recipe_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="veg_recipe",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="veg_recipe",
            name="recipe_image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
