# Generated by Django 4.2.16 on 2024-09-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veg", "0003_veg_recipe_user_alter_veg_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veg_recipe",
            name="recipe_image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="veg_recipe",
            name="recipe_name",
            field=models.CharField(max_length=50),
        ),
    ]
